language: ruby
cache: bundler
services:
  - postgresql
before_install:
  - bundle config trusona.jfrog.io $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml